### ISSUE TITLE
[CodeGen] The C# service code gen project cannot build

### ISSUE THREAD

**Issue by LianwMS** [OData/model-first#150]
Sites: http://apidocument.azurewebsites.net/#/

Inpur: 
```
api:
  name: Service
root:
  - name: Books
    type: Book[]
  - name: OneBlog
    type: Blog
  - name: GetOneBook
    params:
      - name: userId
        type: int
    returns : Book
types:
  - name: Book
    key:
      - name: ID
        type: long
      - name: TestN
        type: long
    dynamic: true
    requiredProperties:
      - Title
      - Author
      - Number
    operations:
      - name: GetTopBook
        params:
          - name: test
            type: int
        returns: Book[]
  - name: Blog
    key:
      - name: ID
        type: long
    requiredProperties: Title

```
Click Generate C# Service code, download and open in VS. Try build:

Error shows:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Application Configuration file "Web.config" is invalid. Root element is missing.	ODataServiceV4Server	C:\Users\lianw\Desktop\odatav4server_20160727053936elyde\odatav4server_20160727053936elyde\odatav4server\Web.config
