### ISSUE TITLE
Add rootUrl to service section

### ISSUE THREAD

**Issue by markdstafford** [OData/model-first#6]
Swagger includes the following in their YAML:

```yaml
host: petstore.swagger.wordnik.com
basePath: /api
schemes:
  - http
```
I think we can simplify this to rootUrl.
