### ISSUE TITLE
Simplify capabilities

### ISSUE THREAD

**Issue by markdstafford** [OData/model-first#7]
Currently capabilities are specified as separate line items, e.g.:

```yaml
insertable: true
searchable: true
deletable: true
```

Simplify these into a single line if possible:

```yaml
allows: [create, read, delete]
